name: Parellel Browsers Chrome-Firefox

on: push

jobs:
  Firefox-Browser-RUN:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            browser: firefox
      - name: Execution Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome Report
          path: cypress/reports/html

  Chrome-Browser-RUN:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            browser: chrome
      - name: Execution Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome Report
          path: cypress/reports/html